### ISSUE TITLE
Add support for sklearn.multioutput.MultiOutputRegressor

### ISSUE THREAD

**Issue by shoegazerstella** [microsoft/hummingbird#400]
Hi, 
Just asking if you have plans for supporting `sklearn.multioutput.MultiOutputRegressor` in the near future.
I get this error when I try to convert my model:

```
Traceback (most recent call last):
  File "inference.py", line 67, in <module>
    main()
  File "inference.py", line 47, in main
    model, model_torch, scaler = load_model()
  File "inference.py", line 20, in load_model
    model_torch = convert(model, 'pytorch', device=device)
  File "/home/stella/Code/.env/lib/python3.7/site-packages/hummingbird/ml/convert.py", line 395, in convert
    return _convert_sklearn(model, backend, test_input, device, extra_config)
  File "/home/stella/Code/.env/lib/python3.7/site-packages/hummingbird/ml/convert.py", line 88, in _convert_sklearn
    topology = parse_sklearn_api_model(model, extra_config)
  File "/home/stella/Code/.env/lib/python3.7/site-packages/hummingbird/ml/_parse.py", line 60, in parse_sklearn_api_model
    outputs = _parse_sklearn_api(scope, model, inputs)
  File "/home/stella/Code/.env/lib/python3.7/site-packages/hummingbird/ml/_parse.py", line 226, in _parse_sklearn_api
    outputs = _parse_sklearn_single_model(scope, model, inputs)
  File "/home/stella/Code/.env/lib/python3.7/site-packages/hummingbird/ml/_parse.py", line 246, in _parse_sklearn_single_model
    alias = get_sklearn_api_operator_name(type(model))
  File "/home/stella/Code/.env/lib/python3.7/site-packages/hummingbird/ml/supported.py", line 355, in get_sklearn_api_operator_name
    raise MissingConverter("Unable to find converter for model type {}.".format(model_type))
hummingbird.ml.exceptions.MissingConverter: Unable to find converter for model type <class 'sklearn.multioutput.MultiOutputRegressor'>.
It usually means the pipeline being converted contains a
transformer or a predictor with no corresponding converter implemented.
Please fill an issue at https://github.com/microsoft/hummingbird.
```

thanks a lot!

**Comment by ksaur** [comment]
Hi @shoegazerstella!  Thanks for posting this! I will add it to the list of [requested operators](https://github.com/microsoft/hummingbird/wiki/Roadmap-for-Upcoming-Features-and-Support#other-features-requested)! :)
