### ISSUE TITLE
Getting error while predict after converting it to pytorch on KMeans model

### ISSUE THREAD

**Issue by muhammad49** [microsoft/hummingbird#482]
I am simply converting my clustering KMeans model like this
**
from hummingbird.ml import convert
model_torch = convert(sklearn_model, 'pytorch')
predicted = model_torch .predict(data)
**
The columns are exactly same but it is showing me the following error and without converting it to pytorch when I use the simple skl-algo it works fine

"Traceback (most recent call last):
  File "/root/anaconda3/envs/pyspark_env/lib/python3.6/site-packages/hummingbird_ml-0.2.2-py3.6.egg/hummingbird/ml/containers/_sklearn_api_containers.py", line 114, in predict
    return self._run(self._predict, *inputs)
  File "/root/anaconda3/envs/pyspark_env/lib/python3.6/site-packages/hummingbird_ml-0.2.2-py3.6.egg/hummingbird/ml/containers/_sklearn_api_containers.py", line 62, in _run
    return function(*inputs)
  File "/root/anaconda3/envs/pyspark_env/lib/python3.6/site-packages/hummingbird_ml-0.2.2-py3.6.egg/hummingbird/ml/containers/sklearn/pytorch_containers.py", line 162, in _predict
    output = self.model.forward(*inputs).cpu().numpy()
  File "/root/anaconda3/envs/pyspark_env/lib/python3.6/site-packages/hummingbird_ml-0.2.2-py3.6.egg/hummingbird/ml/_executor.py", line 70, in forward
    self._input_names
AssertionError: number of inputs or number of columns in the dataframe do not match with the expected number of inputs ['input']
"

**Comment by interesaaat** [comment]
Hi @muhammad49! I think this happens because your input dataset is in pandas dataframe format while by default Hummingbird expects a numpy array. Does it work if you pass `data.values` as input to the predict function?

**Comment by muhammad49** [comment]
Yes it worked. Thanks

**Comment by interesaaat** [comment]
Great!

**Comment by muhammad49** [comment]
After converting it into numpy array it throws the following traceback 
"Traceback (most recent call last):
  File "/root/anaconda3/envs/pyspark_env/lib/python3.6/site-packages/hummingbird_ml-0.2.2-py3.6.egg/hummingbird/ml/containers/_sklearn_api_containers.py", line 114, in predict
    return self._run(self._predict, *inputs)
  File "/root/anaconda3/envs/pyspark_env/lib/python3.6/site-packages/hummingbird_ml-0.2.2-py3.6.egg/hummingbird/ml/containers/_sklearn_api_containers.py", line 62, in _run
    return function(*inputs)
  File "/root/anaconda3/envs/pyspark_env/lib/python3.6/site-packages/hummingbird_ml-0.2.2-py3.6.egg/hummingbird/ml/containers/sklearn/pytorch_containers.py", line 162, in _predict
    output = self.model.forward(*inputs).cpu().numpy()
  File "/root/anaconda3/envs/pyspark_env/lib/python3.6/site-packages/hummingbird_ml-0.2.2-py3.6.egg/hummingbird/ml/_executor.py", line 107, in forward
    outputs = operator(*(variable_map[input_name] for input_name in operator.inputs))
  File "/root/anaconda3/envs/pyspark_env/lib/python3.6/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/root/anaconda3/envs/pyspark_env/lib/python3.6/site-packages/hummingbird_ml-0.2.2-py3.6.egg/hummingbird/ml/operator_converters/sklearn/cluster.py", line 30, in forward
    dist = torch.cdist(x, self.centroids, compute_mode="donot_use_mm_for_euclid_dist")
  File "/root/anaconda3/envs/pyspark_env/lib/python3.6/site-packages/torch/functional.py", line 1123, in cdist
    return _VF.cdist(x1, x2, p, 2)  # type: ignore
RuntimeError: expected scalar type Float but found Double
"

**Comment by muhammad49** [comment]
Can you please re-open this issue or should I post a new issue?

**Comment by interesaaat** [comment]
Let's use another issue for this since it's a different error.
