### ISSUE TITLE
KMeans expect Float but could get Double

### ISSUE THREAD

**Issue by interesaaat** [microsoft/hummingbird#485]
From issue #482. @muhammad49.

After converting it into numpy array it throws the following traceback
"Traceback (most recent call last):
File "/root/anaconda3/envs/pyspark_env/lib/python3.6/site-packages/hummingbird_ml-0.2.2-py3.6.egg/hummingbird/ml/containers/_sklearn_api_containers.py", line 114, in predict
return self._run(self._predict, *inputs)
File "/root/anaconda3/envs/pyspark_env/lib/python3.6/site-packages/hummingbird_ml-0.2.2-py3.6.egg/hummingbird/ml/containers/_sklearn_api_containers.py", line 62, in _run
return function(*inputs)
File "/root/anaconda3/envs/pyspark_env/lib/python3.6/site-packages/hummingbird_ml-0.2.2-py3.6.egg/hummingbird/ml/containers/sklearn/pytorch_containers.py", line 162, in _predict
output = self.model.forward(inputs).cpu().numpy()
File "/root/anaconda3/envs/pyspark_env/lib/python3.6/site-packages/hummingbird_ml-0.2.2-py3.6.egg/hummingbird/ml/_executor.py", line 107, in forward
outputs = operator((variable_map[input_name] for input_name in operator.inputs))
File "/root/anaconda3/envs/pyspark_env/lib/python3.6/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
result = self.forward(*input, **kwargs)
File "/root/anaconda3/envs/pyspark_env/lib/python3.6/site-packages/hummingbird_ml-0.2.2-py3.6.egg/hummingbird/ml/operator_converters/sklearn/cluster.py", line 30, in forward
dist = torch.cdist(x, self.centroids, compute_mode="donot_use_mm_for_euclid_dist")
File "/root/anaconda3/envs/pyspark_env/lib/python3.6/site-packages/torch/functional.py", line 1123, in cdist
return _VF.cdist(x1, x2, p, 2) # type: ignore
RuntimeError: expected scalar type Float but found Double
"

**Comment by interesaaat** [comment]
Duplicate of #486.
