### ISSUE TITLE
onnx->torch bug when no input passed

### ISSUE THREAD

**Issue by ksaur** [microsoft/hummingbird#496]
When we convert from onnx to torch, the converter calculates the expected number of inputs wrong.
Ex:
```
convert(onnx_model, 'torch')
```

We need to force the user to pass some test input along with the conversion to prevent this issue.
Ex:
```
convert(onnx_model, 'torch', data)
```
should work.

For now we can add an `assert` with a helpful error message

**Comment by ksaur** [comment]
I should clarify that this is a _predict-time error_, not runtime error:

```
from hummingbird.ml import convert
import pandas as pd
import onnx # for load from string
s='hospital_LogisticRegression_Binary_l1_0.1_batch.onnx'

with open(s, 'rb') as binary_file:
    mod = binary_file.read()

hbout = convert( onnx.load_from_string(mod),'torch')
# no error

data = pd.read_csv('data.csv')
hbout.predict(data)
```
gives:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/hummingbird/hummingbird/ml/containers/_sklearn_api_containers.py", line 119, in predict
    return self._run(self._predict, *inputs)
  File "/root/hummingbird/hummingbird/ml/containers/_sklearn_api_containers.py", line 67, in _run
    return function(*inputs)
  File "/root/hummingbird/hummingbird/ml/containers/sklearn/pytorch_containers.py", line 192, in _predict
    return self.model.forward(*inputs)[0].cpu().numpy().ravel()
  File "/root/hummingbird/hummingbird/ml/_executor.py", line 73, in forward
    self._input_names
AssertionError: number of inputs or number of columns in the dataframe do not match with the expected number of inputs ['hematocrit', 'neutrophils', 'sodium', 'glucose', 'bloodureanitro', 'creatinine', 'bmi', 'pulse', 'respiration', 'number_of_issues', 'asthma', 'depress', 'dialysisrenalendstage', 'fibrosisandother', 'gender', 'hemo', 'irondef', 'malnutrition', 'pneum', 'psychologicaldisordermajor', 'psychother', 'secondarydiagnosisnonicd9', 'substancedependence', 'rcount']
```

But this works:
```
hbout = convert(onnx.load_from_string(mod),'torch', data)   # pass in some test data

hbout.predict(data)
```

**Comment by ksaur** [comment]
In theory, we shouldn't need to require inputs for onnx->torch, but it seems that our code that processes the onnx inputs fails to get it right in some cases.  (dangling inputs in the model?)  

For now, we'll add an assert.
