### ISSUE TITLE
Better error message needed for bad path

### ISSUE THREAD

**Issue by ksaur** [microsoft/hummingbird#497]
In troubleshooting with a user reporting a `RuntimeError`, he got an unhelpful error message on file not found:

```
model = load(name)
  File "~/hummingbird/hummingbird/ml/_utils.py", line 218, in load
  raise RuntimeError("Model type {} not recognized.".format(model_type))
RuntimeError: Model type not recognized.
```
We later determined that this was due to a bad path.

It would be nice to give an additional error message indicating that the file doesn't exist.

**Comment by ksaur** [comment]
Digging a bit further, i see that on line [205](https://github.com/microsoft/hummingbird/blob/main/hummingbird/ml/_utils.py#L205) we are in fact checking that the file exists.  

I wasn't able to reproduce the bug

**Comment by ksaur** [comment]
```
>>> from hummingbird.ml import load
>>> load('nonsense.zip')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/.local/lib/python3.6/site-packages/hummingbird/ml/_utils.py", line 203, in load
    shutil.unpack_archive(zip_location, location, format="zip")
  File "/usr/lib/python3.6/shutil.py", line 974, in unpack_archive
    func(filename, extract_dir, **dict(format_info[2]))
  File "/usr/lib/python3.6/shutil.py", line 883, in _unpack_zipfile
    raise ReadError("%s is not a zip file" % filename)
shutil.ReadError: nonsense.zip is not a zip file
```
