### ISSUE TITLE
Error with inputs on a model converted onnx->torch

### ISSUE THREAD

**Issue by ksaur** [microsoft/hummingbird#515]
For [this](https://github.com/microsoft/hummingbird/tree/kasaur/onnx_cols_prob/tests/errorcode) model and data, a user reported the following error when converting their model from onnx to torch:

```python
import onnx
from hummingbird.ml import convert
from hummingbird.ml import constants
import pandas as pd

m = "/root/hummingbird/tests/errorcode/mymodel.onnx"
csvstr="/root/hummingbird/tests/errorcode/X.csv"
csv=pd.read_csv(csvstr)

with open(m, 'rb') as binary_file:
    modstr = binary_file.read()

hbout = convert( onnx.load_from_string(modstr),'torch',  csv)

# this will give the error below
hbout.predict(csv)
```

```bash
Traceback (most recent call last):
  File "/root/hummingbird/tests/errorcode/colserror.py", line 16, in <module>
    hbout.predict(csv)
  File "/root/hummingbird/hummingbird/ml/containers/_sklearn_api_containers.py", line 119, in predict
    return self._run(self._predict, *inputs)
  File "/root/hummingbird/hummingbird/ml/containers/_sklearn_api_containers.py", line 67, in _run
    return function(*inputs)
  File "/root/hummingbird/hummingbird/ml/containers/sklearn/pytorch_containers.py", line 192, in _predict
    return self.model.forward(*inputs)[0].cpu().numpy().ravel()
  File "/root/hummingbird/hummingbird/ml/_executor.py", line 73, in forward
    self._input_names
AssertionError: number of inputs or number of columns in the dataframe do not match with the expected number of inputs ['loc', 'v_g_', 'ev_g_', 'iv_g_', 'n', 'v', 'l', 'd', 'i', 'e', 'b', 't', 'lOCode', 'lOComment', 'lOBlank', 'lOCodeAndComment', 'uniq_Op', 'total_Op', 'total_Opnd', 'branchCount']
```

**Comment by ksaur** [comment]
probably related to #513

**Comment by ksaur** [comment]
Ok, the problem is due to the fact that the model has 20 inputs, but the data the user provided has 21 inputs.

In `pytorch_containers.py` we have `extra_config[constants.N_INPUTS]=21`, because we get that out of the test data.

So the user either needs to fix their input data to match the model data, or we need do dig a bit deeper into the onnx model parameters.

**Comment by ksaur** [comment]
Verified that the [correct CSV file](https://raw.githubusercontent.com/microsoft/hummingbird/361277f461b9f80f58936704ff651596bc02e7b4/tests/errorcode/X_pruned.csv) fixes the error; closing
