### ISSUE TITLE
Code coverage

### ISSUE THREAD

**Issue by ksaur** [microsoft/hummingbird#589]
Code coverage dropped to 80% from 90% unexpectedly. TODO: investigate

**Comment by ksaur** [comment]
It looks like the ONNX tests were skipped?
https://app.codecov.io/gh/microsoft/hummingbird/compare/581/changes
https://app.codecov.io/gh/microsoft/hummingbird/commit/65de4b21fbcefa172afaa31f9a2af3590b43a111

**Comment by mshr-h** [comment]
> It looks like the ONNX tests were skipped?

I think that's true.

[Bump TVM to v0.8 (#581) · microsoft/hummingbird@65de4b2](https://github.com/microsoft/hummingbird/runs/6836144312?check_suite_focus=true)
```
Run pytest
============================= test session starts ==============================
platform linux -- Python 3.8.12, pytest-7.1.2, pluggy-1.0.0
rootdir: /home/runner/work/hummingbird/hummingbird
collected 611 items
tests/test_backends.py .....s..sssss....s....................            [  6%]
tests/test_extra_conf.py s.ssssss..s..........................           [ 12%]
tests/test_lightgbm_converter.py ..............s.......................  [ 18%]
tests/test_no_extra_install.py .ss.ss                                    [ 19%]
tests/test_onnxml_binarizer_converter.py sssss                           [ 20%]
tests/test_onnxml_decision_tree_converter.py sssssssssss                 [ 22%]
tests/test_onnxml_imputer_converter.py sssss                             [ 22%]
tests/test_onnxml_label_encoder_converter.py ssss                        [ 23%]
tests/test_onnxml_lightgbm_converter.py sssssssssssssss                  [ 26%]
tests/test_onnxml_linear_converter.py sssss                              [ 26%]
tests/test_onnxml_normalizer_converter.py ssss                           [ 27%]
tests/test_onnxml_one_hot_encoder_converter.py sssss                     [ 28%]
tests/test_onnxml_scaler_converter.py sssssssss                          [ 29%]
tests/test_onnxml_sv_converter.py ss                                     [ 30%]
tests/test_prophet.py ..                                                 [ 30%]
```

[Fix problem with new onnx and protobuf (#582) · microsoft/hummingbird@a67e237](https://github.com/microsoft/hummingbird/runs/6747809647?check_suite_focus=true)
```
Run pytest
============================= test session starts ==============================
platform linux -- Python 3.8.12, pytest-7.1.2, pluggy-1.0.0
rootdir: /home/runner/work/hummingbird/hummingbird
collected 611 items
tests/test_backends.py ......................................            [  6%]
tests/test_extra_conf.py .....................................           [ 12%]
tests/test_lightgbm_converter.py ..............s.......................  [ 18%]
tests/test_no_extra_install.py .sssss                                    [ 19%]
tests/test_onnxml_binarizer_converter.py .....                           [ 20%]
tests/test_onnxml_decision_tree_converter.py ...........                 [ 22%]
tests/test_onnxml_imputer_converter.py .....                             [ 22%]
tests/test_onnxml_label_encoder_converter.py s...                        [ 23%]
tests/test_onnxml_lightgbm_converter.py ...............                  [ 26%]
tests/test_onnxml_linear_converter.py .....                              [ 26%]
tests/test_onnxml_normalizer_converter.py ....                           [ 27%]
tests/test_onnxml_one_hot_encoder_converter.py .....                     [ 28%]
tests/test_onnxml_scaler_converter.py .........                          [ 29%]
tests/test_onnxml_sv_converter.py ..                                     [ 30%]
tests/test_prophet.py ..                                                 [ 30%]
```

**Comment by mshr-h** [comment]
Might be [this change](https://github.com/microsoft/hummingbird/pull/581/commits/53b98ebca5efd38a5691c2eca40723474db204d1) was not correct?

**Comment by mshr-h** [comment]
With `onnxmltools==1.11.1`, `import onnxmltools` will fail and report an error below.
With `onnxmltools==1.11.0`, it works fine.
I think we have to use `onnxmltools==1.11.0`.

```
>>> import onnxmltools
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/.pyenv/versions/hummingbird-debug/lib/python3.8/site-packages/onnxmltools/__init__.py", line 25, in <module>
    from .utils import load_model
  File "/home/ubuntu/.pyenv/versions/hummingbird-debug/lib/python3.8/site-packages/onnxmltools/utils/__init__.py", line 10, in <module>
    from .float16_converter import convert_float_to_float16
  File "/home/ubuntu/.pyenv/versions/hummingbird-debug/lib/python3.8/site-packages/onnxmltools/utils/float16_converter.py", line 4, in <module>
    from onnxconverter_common.auto_mixed_precision import *  # noqa
ModuleNotFoundError: No module named 'onnxconverter_common.auto_mixed_precision'
```
